apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: surveys
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::381491868231:role/ExternalSecretsOperatorRole