# create configmap for cluster name and aws region for CloudWatch Logs
# need to replace the placeholders "topsurvey-dev-eks-cluster" and "eu-west-1"
# and need to replace "Off" and "2020"
# and need to replace "Off" and "On"
apiVersion: v1
data:
  cluster.name: "topsurvey-dev-eks-cluster"
  logs.region: "eu-west-1"
  http.server: "Off"
  http.port: "2020"
  read.head: "Off"
  read.tail: "On"
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info
  namespace: amazon-cloudwatch